#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2011 Mark Streatfield <mstreatfield@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

if __name__ == "__main__":
    """
    In Python 2.7 we'd use Argparse instead, much nicer.
    """
    
    from optparse import OptionParser
    import sys
    import zeromail
    
    usage = "usage: %prog [options]"
    
    parser = OptionParser(usage=usage)
    parser.add_option("-f", "--file", dest="filename", help="Path to the file containing the email dump.", metavar="FILE")
    parser.add_option("-d", "--dump", dest="dump", type="choice", choices=["dict", "vcard"], default="dict", help="Dump mode. ")
    
    options, args = parser.parse_args()
    
    if options.filename is None:
        print "Invalid filename specified."
        sys.exit(1)
    
    extract = zeromail.Extractor()
    extract.load(options.filename)
    extract.parse()
    extract.dump(options.dump)
